export interface AnalyzeResponse {
  sessionId: string;
  fileName: string;
  parsedAt: string;
  totalEntries: number;
  totalEvents: number;
  durationMs: number;
  currentState: string;
  guidanceLevel: string;
  recommendedNextStep: string | null;
  contextNarrative: string;
  detectedUser: string;
  activeEntities: SerializableActiveEntity[];
  workflowHints: string[];
  workflowCandidates: WorkflowCandidateResult[];
  semanticMatches: SemanticWorkflowMatch[];
  ambiguity: AmbiguitySignal | null;
}

export interface WorkflowCandidateResult {
  workflowId: string;
  workflowName: string;
  confidenceScore: number;
  confidenceLevel: string;
  currentStateName: string | null;
  matchedRules: string[];
  matchedEvidence: string[];
  missingRules: string[];
  nextStepHint: string | null;
  scoreBreakdown: Record<string, number>;
  workshopQuestions: string[];
}

export interface WorkflowSummary {
  id: string;
  name: string;
  status: 'Approved' | 'Candidate' | 'Deprecated';
  version: string;
  description: string;
  riskLevel: string;
  tags: string[];
  isValid: boolean;
  ruleCount: number;
  stateCount: number;
  confidenceThreshold: number;
}

export interface WorkflowDefinition {
  workflowId: string;
  name: string;
  description: string;
  version: string;
  status: number;
  activitySignature: ActivitySignatureRule[];
  states: WorkflowState[];
  actions: WorkflowAction[];
  tags: string[];
  minimumConfidenceThreshold: number;
  createdBy: string;
  createdDate: string;
  lastModifiedDate: string;
  metadata: Record<string, unknown>;
  helpGuideIds: string[];
}

export interface ActivitySignatureRule {
  ruleId: string;
  eventType: number;
  recordKind: number;
  workspaceKind: string | null;
  required: boolean;
  weight: number;
  missingPenalty: number;
  maxAgeMinutes: number | null;
  description: string;
}

export interface WorkflowState {
  stateId: string;
  name: string;
  description: string;
  requiredEvidence: string[];
  sequence: number;
  isTerminal: boolean;
  nextStateId: string | null;
  helpGuideId: string;
  workshopQuestions?: string[];
  metadata: Record<string, unknown>;
}

export interface WorkflowAction {
  actionId: string;
  name: string;
  description: string;
  executionMode: number;
  availableInStateId: string;
  metadata: Record<string, unknown>;
}

export interface SerializableActiveEntity {
  recordId: number;
  name: string;
  recordKind: string;
  typeId: number;
  state: string | null;
  lastModified: string;
}

export interface SemanticWorkflowMatch {
  workflowId: string;
  workflowName: string;
  score: number;
  matchedTerms: string[];
  matchedFields: string[];
  reason: string;
}

export interface AmbiguitySignal {
  isAmbiguous: boolean;
  activityMatchId: string | null;
  semanticMatchId: string | null;
  activityConfidence: number;
  semanticScore: number;
  recommendedAction: string;
  clarificationQuestion: string | null;
}

export interface HelpGuideSection {
  sectionId: string;
  heading: string;
  level: number;
  content: string;
  relevantStepIds: string[];
}

export interface HealthCheckResponse {
  status: string;
  workflowCount: number;
}

export interface GuideSuggestion {
  workflowId: string;
  stepId: string;
  suggestedGuideFile: string;
  suggestedSectionId: string | null;
  suggestedSectionHeading: string;
  confidenceReason: string;
  isAutoGenerated: boolean;
}

export interface GuideMapping {
  stepId: string;
  guideFile: string;
  sectionId: string | null;
  isAutoGenerated: boolean;
}

export interface WorkflowGuideMappings {
  workflowId: string;
  mappings: GuideMapping[];
}

export interface WorkflowLibraryItem {
  id: string;
  name: string;
  status: 'Approved' | 'Candidate' | 'Deprecated';
  version: string;
  riskLevel: 'Low' | 'Medium' | 'High';
  tags: string[];
  description: string;
  isValid: boolean;
  validationErrors: string[];
  ruleCount: number;
  stateCount: number;
  lastModified: string;
  fileName: string;
}

export interface WorkflowVariant {
  variantId: string;
  description: string;
  differentSteps: string[];
  occurrenceCount: number;
  percentage: number;
}

export interface InferredWorkflowSuggestion {
  suggestedName: string;
  suggestedDescription: string;
  suggestedRiskLevel: 'Low' | 'Medium' | 'High';
  suggestedTags: string[];
  suggestedRules: ActivitySignatureRule[];
  suggestedStates: WorkflowStateDefinition[];
  suggestedThreshold: number;
  variants: WorkflowVariant[];
  evidenceSessions: number;
  evidenceEvents: number;
  inferenceNotes: string[];
}

export interface WorkflowStateDefinition {
  stateId: string;
  stateName: string;
  description: string;
  nextStepHint?: string;
  isTerminal: boolean;
}

export interface InferredNameSuggestion {
  suggestedName: string;
  suggestedDescription: string;
  alternativeNames: string[];
}

export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
  toolsUsed: string[];
}

export interface ChatSession {
  sessionId: string;
  createdAt: string;
  lastActivityAt: string;
  messages: ChatMessage[];
  logFileName: string | null;
  analyzeResponse: AnalyzeResponse | null;
}

export interface ChatRequest {
  sessionId?: string;
  message: string;
  logContent?: string;
  userName?: string;
  userQuestion?: string;
}

export interface ChatResponse {
  sessionId: string;
  reply: string;
  toolsUsed: string[];
  workflowContext: string | null;
  sources: string[];
}
