using Aktavara.WorkflowIntelligence.Core.Interfaces;
using Aktavara.WorkflowIntelligence.Core.Models;
using Microsoft.Extensions.Logging;

namespace Aktavara.WorkflowIntelligence.Core.Services;

/// <summary>
/// Loads help guides from markdown files with YAML front matter.
/// </summary>
public class FileHelpGuideStore : IHelpGuideStore
{
    private readonly string _helpGuidesPath;
    private readonly ILogger<FileHelpGuideStore> _logger;
    private List<HelpGuide>? _cache;
    private bool _loaded;

    public FileHelpGuideStore(string helpGuidesPath, ILogger<FileHelpGuideStore> logger)
    {
        _helpGuidesPath = helpGuidesPath;
        _logger = logger;
        _loaded = false;
    }

    public HelpGuide? GetById(string helpGuideId)
    {
        EnsureLoaded();
        return _cache?.FirstOrDefault(g => g.HelpGuideId == helpGuideId);
    }

    public IReadOnlyList<HelpGuide> GetByWorkflowId(string workflowId)
    {
        EnsureLoaded();
        return _cache?.Where(g => g.WorkflowId == workflowId).ToList() ?? new List<HelpGuide>();
    }

    public IReadOnlyList<HelpGuide> GetByStepId(string workflowId, string stepId)
    {
        EnsureLoaded();
        return _cache?.Where(g => g.WorkflowId == workflowId && g.StepId == stepId).ToList() ?? new List<HelpGuide>();
    }

    public IReadOnlyList<HelpGuide> GetAll()
    {
        EnsureLoaded();
        return _cache?.AsReadOnly() ?? new List<HelpGuide>().AsReadOnly();
    }

    private void EnsureLoaded()
    {
        if (_loaded)
            return;

        _cache = new List<HelpGuide>();
        _loaded = true;

        if (!Directory.Exists(_helpGuidesPath))
        {
            _logger.LogInformation("Help guides directory not found at {Path}", _helpGuidesPath);
            return;
        }

        try
        {
            var mdFiles = Directory.GetFiles(_helpGuidesPath, "*.md", SearchOption.AllDirectories);
            _logger.LogInformation("Found {Count} help guide files", mdFiles.Length);

            foreach (var filePath in mdFiles)
            {
                try
                {
                    var guide = ParseHelpGuideFile(filePath);
                    if (guide != null)
                    {
                        _cache.Add(guide);
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogWarning(ex, "Error parsing help guide file {FilePath}", filePath);
                }
            }

            _logger.LogInformation("Loaded {Count} help guides", _cache.Count);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error loading help guides from {Path}", _helpGuidesPath);
        }
    }

    private HelpGuide? ParseHelpGuideFile(string filePath)
    {
        var content = File.ReadAllText(filePath);

        // Parse YAML front matter
        var frontMatterMatch = System.Text.RegularExpressions.Regex.Match(
            content,
            @"^---\s*\n(.*?)\n---\s*\n(.*)$",
            System.Text.RegularExpressions.RegexOptions.Singleline);

        if (!frontMatterMatch.Success)
        {
            _logger.LogWarning("No YAML front matter found in {FilePath}", filePath);
            return null;
        }

        var frontMatter = frontMatterMatch.Groups[1].Value;
        var markdown = frontMatterMatch.Groups[2].Value;

        var guide = new HelpGuide();
        guide.MarkdownContent = markdown.Trim();
        guide.LastModified = File.GetLastWriteTimeUtc(filePath);

        // Parse front matter key-value pairs
        foreach (var line in frontMatter.Split('\n'))
        {
            var trimmed = line.Trim();
            if (string.IsNullOrEmpty(trimmed))
                continue;

            var colonIndex = trimmed.IndexOf(':');
            if (colonIndex < 0)
                continue;

            var key = trimmed[..colonIndex].Trim();
            var value = trimmed[(colonIndex + 1)..].Trim();

            switch (key.ToLowerInvariant())
            {
                case "helpguideid":
                    guide.HelpGuideId = value;
                    break;
                case "workflowid":
                    guide.WorkflowId = value;
                    break;
                case "stepid":
                    guide.StepId = value;
                    break;
                case "title":
                    guide.Title = value;
                    break;
                case "tags":
                    guide.Tags = value.Split(',').Select(t => t.Trim()).Where(t => !string.IsNullOrEmpty(t)).ToList();
                    break;
                case "isautogenerated":
                    if (bool.TryParse(value, out var isAuto))
                        guide.IsAutoGenerated = isAuto;
                    break;
            }
        }

        // Validate required fields
        if (string.IsNullOrEmpty(guide.HelpGuideId) ||
            string.IsNullOrEmpty(guide.WorkflowId) ||
            string.IsNullOrEmpty(guide.StepId) ||
            string.IsNullOrEmpty(guide.Title))
        {
            _logger.LogWarning(
                "Help guide file missing required fields (helpGuideId, workflowId, stepId, title): {FilePath}",
                filePath);
            return null;
        }

        return guide;
    }
}
