namespace Aktavara.WorkflowIntelligence.Core.Models;

/// <summary>
/// Represents an LLM-suggested help guide mapping for a workflow step.
/// </summary>
public class GuideSuggestion
{
    public string WorkflowId { get; set; } = string.Empty;
    public string StepId { get; set; } = string.Empty;
    public string SuggestedGuideFile { get; set; } = string.Empty;
    public string? SuggestedSectionId { get; set; }
    public string SuggestedSectionHeading { get; set; } = string.Empty;
    public string ConfidenceReason { get; set; } = string.Empty;
    public bool IsAutoGenerated { get; set; } = true;
}
