namespace Aktavara.WorkflowIntelligence.Core.Models;

/// <summary>
/// A help guide providing step-by-step instructions for workflow execution.
/// </summary>
public class HelpGuide
{
    public string HelpGuideId { get; set; } = string.Empty;
    public string Title { get; set; } = string.Empty;
    public string WorkflowId { get; set; } = string.Empty;
    public string StepId { get; set; } = string.Empty;
    public string MarkdownContent { get; set; } = string.Empty;
    public List<string> Tags { get; set; } = new();
    public DateTime LastModified { get; set; }
    public bool IsAutoGenerated { get; set; }
}
