using Aktavara.WorkflowIntelligence.Core.Interfaces;
using Aktavara.WorkflowIntelligence.Core.Services;
using Xunit;

namespace Aktavara.WorkflowIntelligence.Tests;

/// <summary>
/// Tests for the FileHelpGuideStore service.
/// </summary>
public class FileHelpGuideStoreTests
{
    private static string GetHelpGuidesPath()
    {
        var currentDir = AppContext.BaseDirectory;
        for (int i = 0; i < 10; i++)
        {
            if (Directory.Exists(Path.Combine(currentDir, "help-guides")))
                return Path.Combine(currentDir, "help-guides");
            var parent = Path.GetDirectoryName(currentDir);
            if (parent == null || parent == currentDir)
                break;
            currentDir = parent;
        }
        return Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "help-guides");
    }

    /// <summary>
    /// Test 1: Load help guides from folder → returns correct count
    /// </summary>
    [Fact]
    public void LoadHelpGuides_FromFolder_ReturnsCorrectCount()
    {
        var helpGuidesPath = GetHelpGuidesPath();
        var store = new FileHelpGuideStore(
            helpGuidesPath,
            new Microsoft.Extensions.Logging.Abstractions.NullLogger<FileHelpGuideStore>());

        var allGuides = store.GetAll();

        Assert.NotEmpty(allGuides);
        Assert.True(allGuides.Count >= 4, "Should have at least 4 help guides");
    }

    /// <summary>
    /// Test 2: GetById returns correct guide
    /// </summary>
    [Fact]
    public void GetById_WithValidId_ReturnsCorrectGuide()
    {
        var helpGuidesPath = GetHelpGuidesPath();
        var store = new FileHelpGuideStore(
            helpGuidesPath,
            new Microsoft.Extensions.Logging.Abstractions.NullLogger<FileHelpGuideStore>());

        var guide = store.GetById("save-modified-node");

        Assert.NotNull(guide);
        Assert.Equal("save-modified-node", guide.HelpGuideId);
        Assert.Equal("Save a modified node in a path workspace", guide.Title);
        Assert.Equal("update-node-in-path", guide.WorkflowId);
    }

    /// <summary>
    /// Test 3: GetByWorkflowId returns only matching guides
    /// </summary>
    [Fact]
    public void GetByWorkflowId_ReturnsOnlyMatchingGuides()
    {
        var helpGuidesPath = GetHelpGuidesPath();
        var store = new FileHelpGuideStore(
            helpGuidesPath,
            new Microsoft.Extensions.Logging.Abstractions.NullLogger<FileHelpGuideStore>());

        var guides = store.GetByWorkflowId("update-node-in-path");

        Assert.NotEmpty(guides);
        Assert.All(guides, g => Assert.Equal("update-node-in-path", g.WorkflowId));
    }

    /// <summary>
    /// Test 4: GetByStepId returns guides for that step
    /// </summary>
    [Fact]
    public void GetByStepId_ReturnsGuidesForStep()
    {
        var helpGuidesPath = GetHelpGuidesPath();
        var store = new FileHelpGuideStore(
            helpGuidesPath,
            new Microsoft.Extensions.Logging.Abstractions.NullLogger<FileHelpGuideStore>());

        var guides = store.GetByStepId("update-node-in-path", "node_modified");

        Assert.NotEmpty(guides);
        Assert.All(guides, g => Assert.Equal("node_modified", g.StepId));
    }

    /// <summary>
    /// Test 5: Front matter parsed correctly (all fields)
    /// </summary>
    [Fact]
    public void FrontMatter_ParsedCorrectly_AllFields()
    {
        var helpGuidesPath = GetHelpGuidesPath();
        var store = new FileHelpGuideStore(
            helpGuidesPath,
            new Microsoft.Extensions.Logging.Abstractions.NullLogger<FileHelpGuideStore>());

        var guide = store.GetById("open-path-workspace");

        Assert.NotNull(guide);
        Assert.NotEmpty(guide.Tags);
        Assert.False(guide.IsAutoGenerated);
        Assert.NotNull(guide.MarkdownContent);
        Assert.NotEmpty(guide.MarkdownContent);
    }

    /// <summary>
    /// Test 6: MarkdownContent preserved correctly
    /// </summary>
    [Fact]
    public void MarkdownContent_PreservedCorrectly()
    {
        var helpGuidesPath = GetHelpGuidesPath();
        var store = new FileHelpGuideStore(
            helpGuidesPath,
            new Microsoft.Extensions.Logging.Abstractions.NullLogger<FileHelpGuideStore>());

        var guide = store.GetById("save-connector");

        Assert.NotNull(guide);
        Assert.Contains("# Save a Newly Created Connector", guide.MarkdownContent);
        Assert.True(guide.MarkdownContent.Length > 100);
    }

    /// <summary>
    /// Test 7: GetById with nonexistent ID returns null
    /// </summary>
    [Fact]
    public void GetById_WithInvalidId_ReturnsNull()
    {
        var helpGuidesPath = GetHelpGuidesPath();
        var store = new FileHelpGuideStore(
            helpGuidesPath,
            new Microsoft.Extensions.Logging.Abstractions.NullLogger<FileHelpGuideStore>());

        var guide = store.GetById("nonexistent-guide");

        Assert.Null(guide);
    }

    /// <summary>
    /// Test 8: GetAll returns all loaded guides
    /// </summary>
    [Fact]
    public void GetAll_ReturnsAllLoadedGuides()
    {
        var helpGuidesPath = GetHelpGuidesPath();
        var store = new FileHelpGuideStore(
            helpGuidesPath,
            new Microsoft.Extensions.Logging.Abstractions.NullLogger<FileHelpGuideStore>());

        var allGuides = store.GetAll();
        var byWorkflow1 = store.GetByWorkflowId("update-node-in-path");
        var byWorkflow2 = store.GetByWorkflowId("add-connector-to-path");

        Assert.NotEmpty(allGuides);
        Assert.True(byWorkflow1.Count + byWorkflow2.Count <= allGuides.Count);
    }

    /// <summary>
    /// Test 9: AssistantContextPacket includes RelevantHelpGuides
    /// </summary>
    [Fact]
    public void AssistantContextPacket_IncludesRelevantHelpGuides()
    {
        var helpGuidesPath = GetHelpGuidesPath();
        var store = new FileHelpGuideStore(
            helpGuidesPath,
            new Microsoft.Extensions.Logging.Abstractions.NullLogger<FileHelpGuideStore>());

        var packet = new Core.Models.AssistantContextPacket
        {
            HelpGuideReferences = new()
            {
                new Core.Models.HelpGuideReference
                {
                    GuideId = "save-modified-node",
                    Title = "Save a modified node",
                    WorkflowId = "update-node-in-path",
                    StateId = "node_modified"
                }
            }
        };

        Assert.NotEmpty(packet.HelpGuideReferences);
        Assert.Single(packet.HelpGuideReferences);
    }
}
